[package]
name = "hiview"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
hashbrown = "0.14.3"
lru = "0.12.3"
notatin = "1.0.1"
ratatui = "0.26.1"
