name: CI
run-name: "triggered by: ${{ github.actor }}"

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-build-validity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Build
        run: cargo build --all-targets
